using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ChampionSelector : MonoBehaviour
{
    [SerializeField]
    Toggle _ASHESelector;

    [SerializeField]
    Toggle _BLITZCRANKSelector;

    [SerializeField]
    Toggle _ELISESelector;

    [SerializeField]
    Toggle _JAXSelector;

    [SerializeField]
    Toggle _JAYCESelector;

    [SerializeField]
    Toggle _LILLIASelector;

    [SerializeField]
    Toggle _NOMSYSelector;

    [SerializeField]
    Toggle _POPPYSelector;

    [SerializeField]
    Toggle _SERAPHINESelector;

    [SerializeField]
    Toggle _SORAKASelector;

    [SerializeField]
    Toggle _TWITCHSelector;

    [SerializeField]
    Toggle _WARWICKSelector;

    [SerializeField]
    Toggle _ZIGGSSelector;

    [SerializeField]
    Toggle _ZOESelector;

    [SerializeField]
    Toggle _AHRISelector;

    [SerializeField]
    Toggle _AKALISelector;

    [SerializeField]
    Toggle _CASSIOPEIASelector;

    [SerializeField]
    Toggle _GALIOSelector;

    [SerializeField]
    Toggle _KASSADINSelector;

    [SerializeField]
    Toggle _KOGMAWSelector;

    [SerializeField]
    Toggle _NILAHSelector;

    [SerializeField]
    Toggle _NUNUSelector;

    [SerializeField]
    Toggle _RUMBLESelector;

    [SerializeField]
    Toggle _SHYVANASelector;

    [SerializeField]
    Toggle _SYNDRASelector;

    [SerializeField]
    Toggle _TRISTANASelector;

    [SerializeField]
    Toggle _ZILEANSelector;

    [SerializeField]
    Toggle _BARDSelector;

    [SerializeField]
    Toggle _EZREALSelector;

    [SerializeField]
    Toggle _HECARIMSelector;

    [SerializeField]
    Toggle _HWEISelector;

    [SerializeField]
    Toggle _JINXSelector;

    [SerializeField]
    Toggle _KATARINASelector;

    [SerializeField]
    Toggle _MORDEKAISERSelector;

    [SerializeField]
    Toggle _NEEKOSelector;

    [SerializeField]
    Toggle _SHENSelector;

    [SerializeField]
    Toggle _SWAINSelector;

    [SerializeField]
    Toggle _VEIGARSelector;

    [SerializeField]
    Toggle _VEXSelector;

    [SerializeField]
    Toggle _WUKONGSelector;

    [SerializeField]
    Toggle _FIORASelector;

    [SerializeField]
    Toggle _GWENSelector;

    [SerializeField]
    Toggle _KALISTASelector;

    [SerializeField]
    Toggle _KARMASelector;

    [SerializeField]
    Toggle _NAMISelector;

    [SerializeField]
    Toggle _NASUSSelector;

    [SerializeField]
    Toggle _OLAFSelector;

    [SerializeField]
    Toggle _RAKANSelector;

    [SerializeField]
    Toggle _RYZESelector;

    [SerializeField]
    Toggle _TAHMKENCHSelector;

    [SerializeField]
    Toggle _TARICSelector;

    [SerializeField]
    Toggle _VARUSSelector;

    [SerializeField]
    Toggle _BRIARSelector;

    [SerializeField]
    Toggle _CAMILLESelector;

    [SerializeField]
    Toggle _DIANASelector;

    [SerializeField]
    Toggle _MILLIOSelector;

    [SerializeField]
    Toggle _MORGANASelector;

    [SerializeField]
    Toggle _NORRASelector;

    [SerializeField]
    Toggle _SMOLDERSelector;

    [SerializeField]
    Toggle _XERATHSelector;


    public HashSet<ChampionsEnum> GetSelectedChampions()
    {
        var selectedChampions = new HashSet<ChampionsEnum>();

        if (_ASHESelector.isOn) selectedChampions.Add(ChampionsEnum.ASHE);
        if (_BLITZCRANKSelector.isOn) selectedChampions.Add(ChampionsEnum.BLITZCRANK);
        if (_ELISESelector.isOn) selectedChampions.Add(ChampionsEnum.ELISE);
        if (_JAXSelector.isOn) selectedChampions.Add(ChampionsEnum.JAX);
        if (_JAYCESelector.isOn) selectedChampions.Add(ChampionsEnum.JAYCE);
        if (_LILLIASelector.isOn) selectedChampions.Add(ChampionsEnum.LILLIA);
        if (_NOMSYSelector.isOn) selectedChampions.Add(ChampionsEnum.NOMSY);
        if (_POPPYSelector.isOn) selectedChampions.Add(ChampionsEnum.POPPY);
        if (_SERAPHINESelector.isOn) selectedChampions.Add(ChampionsEnum.SERAPHINE);
        if (_SORAKASelector.isOn) selectedChampions.Add(ChampionsEnum.SORAKA);
        if (_TWITCHSelector.isOn) selectedChampions.Add(ChampionsEnum.TWITCH);
        if (_WARWICKSelector.isOn) selectedChampions.Add(ChampionsEnum.WARWICK);
        if (_ZIGGSSelector.isOn) selectedChampions.Add(ChampionsEnum.ZIGGS);
        if (_ZOESelector.isOn) selectedChampions.Add(ChampionsEnum.ZOE);
        if (_AHRISelector.isOn) selectedChampions.Add(ChampionsEnum.AHRI);
        if (_AKALISelector.isOn) selectedChampions.Add(ChampionsEnum.AKALI);
        if (_CASSIOPEIASelector.isOn) selectedChampions.Add(ChampionsEnum.CASSIOPEIA);
        if (_GALIOSelector.isOn) selectedChampions.Add(ChampionsEnum.GALIO);
        if (_KASSADINSelector.isOn) selectedChampions.Add(ChampionsEnum.KASSADIN);
        if (_KOGMAWSelector.isOn) selectedChampions.Add(ChampionsEnum.KOGMAW);
        if (_NILAHSelector.isOn) selectedChampions.Add(ChampionsEnum.NILAH);
        if (_NUNUSelector.isOn) selectedChampions.Add(ChampionsEnum.NUNU);
        if (_RUMBLESelector.isOn) selectedChampions.Add(ChampionsEnum.RUMBLE);
        if (_SHYVANASelector.isOn) selectedChampions.Add(ChampionsEnum.SHYVANA);
        if (_SYNDRASelector.isOn) selectedChampions.Add(ChampionsEnum.SYNDRA);
        if (_TRISTANASelector.isOn) selectedChampions.Add(ChampionsEnum.TRISTANA);
        if (_ZILEANSelector.isOn) selectedChampions.Add(ChampionsEnum.ZILEAN);
        if (_BARDSelector.isOn) selectedChampions.Add(ChampionsEnum.BARD);
        if (_EZREALSelector.isOn) selectedChampions.Add(ChampionsEnum.EZREAL);
        if (_HECARIMSelector.isOn) selectedChampions.Add(ChampionsEnum.HECARIM);
        if (_HWEISelector.isOn) selectedChampions.Add(ChampionsEnum.HWEI);
        if (_JINXSelector.isOn) selectedChampions.Add(ChampionsEnum.JINX);
        if (_KATARINASelector.isOn) selectedChampions.Add(ChampionsEnum.KATARINA);
        if (_MORDEKAISERSelector.isOn) selectedChampions.Add(ChampionsEnum.MORDEKAISER);
        if (_NEEKOSelector.isOn) selectedChampions.Add(ChampionsEnum.NEEKO);
        if (_SHENSelector.isOn) selectedChampions.Add(ChampionsEnum.SHEN);
        if (_SWAINSelector.isOn) selectedChampions.Add(ChampionsEnum.SWAIN);
        if (_VEIGARSelector.isOn) selectedChampions.Add(ChampionsEnum.VEIGAR);
        if (_VEXSelector.isOn) selectedChampions.Add(ChampionsEnum.VEX);
        if (_WUKONGSelector.isOn) selectedChampions.Add(ChampionsEnum.WUKONG);
        if (_FIORASelector.isOn) selectedChampions.Add(ChampionsEnum.FIORA);
        if (_GWENSelector.isOn) selectedChampions.Add(ChampionsEnum.GWEN);
        if (_KALISTASelector.isOn) selectedChampions.Add(ChampionsEnum.KALISTA);
        if (_KARMASelector.isOn) selectedChampions.Add(ChampionsEnum.KARMA);
        if (_NAMISelector.isOn) selectedChampions.Add(ChampionsEnum.NAMI);
        if (_NASUSSelector.isOn) selectedChampions.Add(ChampionsEnum.NASUS);
        if (_OLAFSelector.isOn) selectedChampions.Add(ChampionsEnum.OLAF);
        if (_RAKANSelector.isOn) selectedChampions.Add(ChampionsEnum.RAKAN);
        if (_RYZESelector.isOn) selectedChampions.Add(ChampionsEnum.RYZE);
        if (_TAHMKENCHSelector.isOn) selectedChampions.Add(ChampionsEnum.TAHMKENCH);
        if (_TARICSelector.isOn) selectedChampions.Add(ChampionsEnum.TARIC);
        if (_VARUSSelector.isOn) selectedChampions.Add(ChampionsEnum.VARUS);
        if (_BRIARSelector.isOn) selectedChampions.Add(ChampionsEnum.BRIAR);
        if (_CAMILLESelector.isOn) selectedChampions.Add(ChampionsEnum.CAMILLE);
        if (_DIANASelector.isOn) selectedChampions.Add(ChampionsEnum.DIANA);
        if (_MILLIOSelector.isOn) selectedChampions.Add(ChampionsEnum.MILLIO);
        if (_MORGANASelector.isOn) selectedChampions.Add(ChampionsEnum.MORGANA);
        if (_NORRASelector.isOn) selectedChampions.Add(ChampionsEnum.NORRA);
        if (_SMOLDERSelector.isOn) selectedChampions.Add(ChampionsEnum.SMOLDER);
        if (_XERATHSelector.isOn) selectedChampions.Add(ChampionsEnum.XERATH);

        return selectedChampions;
    }

    public void Reset()
    {
        _ASHESelector.enabled = true;
        _BLITZCRANKSelector.enabled = true;
        _ELISESelector.enabled = true;
        _JAXSelector.enabled = true;
        _JAYCESelector.enabled = true;
        _LILLIASelector.enabled = true;
        _NOMSYSelector.enabled = true;
        _POPPYSelector.enabled = true;
        _SERAPHINESelector.enabled = true;
        _SORAKASelector.enabled = true;
        _TWITCHSelector.enabled = true;
        _WARWICKSelector.enabled = true;
        _ZIGGSSelector.enabled = true;
        _ZOESelector.enabled = true;
        _AHRISelector.enabled = true;
        _AKALISelector.enabled = true;
        _CASSIOPEIASelector.enabled = true;
        _GALIOSelector.enabled = true;
        _KASSADINSelector.enabled = true;
        _KOGMAWSelector.enabled = true;
        _NILAHSelector.enabled = true;
        _NUNUSelector.enabled = true;
        _RUMBLESelector.enabled = true;
        _SHYVANASelector.enabled = true;
        _SYNDRASelector.enabled = true;
        _TRISTANASelector.enabled = true;
        _ZILEANSelector.enabled = true;
        _BARDSelector.enabled = true;
        _EZREALSelector.enabled = true;
        _HECARIMSelector.enabled = true;
        _HWEISelector.enabled = true;
        _JINXSelector.enabled = true;
        _KATARINASelector.enabled = true;
        _MORDEKAISERSelector.enabled = true;
        _NEEKOSelector.enabled = true;
        _SHENSelector.enabled = true;
        _SWAINSelector.enabled = true;
        _VEIGARSelector.enabled = true;
        _VEXSelector.enabled = true;
        _WUKONGSelector.enabled = true;
        _FIORASelector.enabled = true;
        _GWENSelector.enabled = true;
        _KALISTASelector.enabled = true;
        _KARMASelector.enabled = true;
        _NAMISelector.enabled = true;
        _NASUSSelector.enabled = true;
        _OLAFSelector.enabled = true;
        _RAKANSelector.enabled = true;
        _RYZESelector.enabled = true;
        _TAHMKENCHSelector.enabled = true;
        _TARICSelector.enabled = true;
        _VARUSSelector.enabled = true;
        _BRIARSelector.enabled = true;
        _CAMILLESelector.enabled = true;
        _DIANASelector.enabled = true;
        _MILLIOSelector.enabled = true;
        _MORGANASelector.enabled = true;
        _NORRASelector.enabled = true;
        _SMOLDERSelector.enabled = true;
        _XERATHSelector.enabled = true;
    }
}
